-- Move room readings out of nodered_sensors into their own table.
create table if not exists public.current_readings (
  id bigint generated by default as identity primary key,
  reading jsonb not null,
  created_at timestamptz not null default now(),
  constraint current_readings_reading_is_object
    check (jsonb_typeof(reading) = 'object'),
  constraint current_readings_reading_has_required_fields
    check (
      reading ? 'room'
      and reading ? 'kWh'
      and reading ? 'timestamp'
    )
);

-- Preserve any batches already written to nodered_sensors before removing the
-- temporary column. The NOT EXISTS guard makes this safe to run more than once.
do $$
begin
  if exists (
    select 1
      from information_schema.columns
     where table_schema = 'public'
       and table_name = 'nodered_sensors'
       and column_name = 'current_readings'
  ) then
    insert into public.current_readings (reading)
    select item.reading
      from public.nodered_sensors ns
      cross join lateral jsonb_array_elements(ns.current_readings) as item(reading)
     where jsonb_typeof(ns.current_readings) = 'array'
       and jsonb_array_length(ns.current_readings) > 0
       and not exists (
         select 1
           from public.current_readings cr
          where cr.reading = item.reading
       );

    alter table public.nodered_sensors
      drop constraint if exists nodered_sensors_current_readings_is_array;

    alter table public.nodered_sensors
      drop column current_readings;
  end if;
end $$;
