-- Store each user's energy target configuration separately from patient_status.
create table if not exists public.setup_energy (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_start_date date not null,
  target_end_date date not null,
  sala_kwh numeric(12, 3) not null default 0,
  living_room_kwh numeric(12, 3) not null default 0,
  master_bedroom_kwh numeric(12, 3) not null default 0,
  rate_per_kwh numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint setup_energy_user_unique unique (user_id),
  constraint setup_energy_dates_valid check (target_end_date >= target_start_date),
  constraint setup_energy_values_nonnegative check (
    sala_kwh >= 0
    and living_room_kwh >= 0
    and master_bedroom_kwh >= 0
    and rate_per_kwh >= 0
  )
);

alter table public.setup_energy enable row level security;

drop policy if exists setup_energy_select_own on public.setup_energy;
create policy setup_energy_select_own
  on public.setup_energy
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists setup_energy_insert_own on public.setup_energy;
create policy setup_energy_insert_own
  on public.setup_energy
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists setup_energy_update_own on public.setup_energy;
create policy setup_energy_update_own
  on public.setup_energy
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
